import { FilipinoRecipe } from "./types";

export const SERVINGS = 4;

export const FILIPINO_RECIPES: FilipinoRecipe[] = [
  {
    id: "adobo-chicken",
    name: "Chicken Adobo",
    nameTl: "Adobong Manok",
    protein: "chicken",
    baseServings: 4,
    prepMinutes: 15,
    cookMinutes: 40,
    ingredients: [
      { name: "chicken thighs", quantity: 1.2, unit: "kg" },
      { name: "soy sauce", quantity: 80, unit: "ml" },
      { name: "vinegar", quantity: 60, unit: "ml" },
      { name: "garlic", quantity: 8, unit: "cloves" },
      { name: "bay leaves", quantity: 3, unit: "pcs" },
      { name: "black pepper", quantity: 1, unit: "tsp" },
    ],
    steps: [
      "Marinate chicken in soy sauce, vinegar, garlic, and pepper 20 min.",
      "Simmer in marinade until tender; reduce sauce.",
      "Serve with rice.",
    ],
  },
  {
    id: "sinigang-pork",
    name: "Sinigang na Baboy",
    nameTl: "Sinigang na Baboy",
    protein: "pork",
    baseServings: 4,
    prepMinutes: 20,
    cookMinutes: 45,
    ingredients: [
      { name: "pork ribs", quantity: 1, unit: "kg" },
      { name: "tamarind mix", quantity: 2, unit: "pack" },
      { name: "kangkong", quantity: 2, unit: "bunch" },
      { name: "tomato", quantity: 2, unit: "pcs" },
      { name: "onion", quantity: 1, unit: "pcs" },
      { name: "radish", quantity: 1, unit: "pcs" },
    ],
    steps: ["Boil pork until tender.", "Add tamarind and vegetables.", "Season and serve hot."],
  },
  {
    id: "tinola",
    name: "Tinolang Manok",
    nameTl: "Tinola",
    protein: "chicken",
    baseServings: 4,
    prepMinutes: 15,
    cookMinutes: 35,
    ingredients: [
      { name: "chicken pieces", quantity: 1, unit: "kg" },
      { name: "ginger", quantity: 50, unit: "g" },
      { name: "chayote", quantity: 2, unit: "pcs" },
      { name: "malunggay", quantity: 2, unit: "cup" },
      { name: "fish sauce", quantity: 2, unit: "tbsp" },
    ],
    steps: ["Sauté ginger and chicken.", "Add water and chayote.", "Finish with malunggay."],
  },
  {
    id: "kare-kare",
    name: "Kare-Kare",
    nameTl: "Kare-Kare",
    protein: "beef",
    baseServings: 4,
    prepMinutes: 25,
    cookMinutes: 60,
    ingredients: [
      { name: "oxtail", quantity: 1, unit: "kg" },
      { name: "peanut butter", quantity: 200, unit: "g" },
      { name: "eggplant", quantity: 2, unit: "pcs" },
      { name: "banana blossom", quantity: 1, unit: "can" },
      { name: "bagoong", quantity: 4, unit: "tbsp" },
    ],
    steps: ["Simmer oxtail until tender.", "Add peanut sauce and vegetables.", "Serve with bagoong."],
  },
  {
    id: "pinakbet",
    name: "Pinakbet",
    nameTl: "Pinakbet",
    protein: "veg",
    baseServings: 4,
    prepMinutes: 20,
    cookMinutes: 25,
    ingredients: [
      { name: "bagnet", quantity: 300, unit: "g" },
      { name: "bitter melon", quantity: 2, unit: "pcs" },
      { name: "eggplant", quantity: 2, unit: "pcs" },
      { name: "okra", quantity: 200, unit: "g" },
      { name: "bagoong", quantity: 3, unit: "tbsp" },
    ],
    steps: ["Sauté bagnet and aromatics.", "Add vegetables and bagoong.", "Cook until crisp-tender."],
  },
  {
    id: "bistek",
    name: "Bistek Tagalog",
    nameTl: "Bistek",
    protein: "beef",
    baseServings: 4,
    prepMinutes: 15,
    cookMinutes: 25,
    ingredients: [
      { name: "beef sirloin", quantity: 700, unit: "g" },
      { name: "soy sauce", quantity: 60, unit: "ml" },
      { name: "calamansi", quantity: 6, unit: "pcs" },
      { name: "onion", quantity: 2, unit: "pcs" },
    ],
    steps: ["Marinate beef in soy and calamansi.", "Pan-fry beef; top with onion rings."],
  },
  {
    id: "ginisang-monggo",
    name: "Ginisang Monggo",
    nameTl: "Ginisang Monggo",
    protein: "veg",
    baseServings: 4,
    prepMinutes: 15,
    cookMinutes: 40,
    ingredients: [
      { name: "mung beans", quantity: 2, unit: "cup" },
      { name: "malunggay", quantity: 2, unit: "cup" },
      { name: "pork", quantity: 300, unit: "g" },
      { name: "garlic", quantity: 4, unit: "cloves" },
      { name: "fish sauce", quantity: 2, unit: "tbsp" },
    ],
    steps: ["Boil mung beans until soft.", "Sauté pork and aromatics; combine.", "Add malunggay."],
  },
  {
    id: "paksiw-bangus",
    name: "Paksiw na Bangus",
    nameTl: "Paksiw na Bangus",
    protein: "fish",
    baseServings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    ingredients: [
      { name: "milkfish", quantity: 1, unit: "kg" },
      { name: "vinegar", quantity: 200, unit: "ml" },
      { name: "ginger", quantity: 30, unit: "g" },
      { name: "eggplant", quantity: 1, unit: "pcs" },
      { name: "peppercorn", quantity: 1, unit: "tsp" },
    ],
    steps: ["Layer fish with vinegar and ginger.", "Simmer until cooked through."],
  },
  {
    id: "menudo",
    name: "Menudo",
    nameTl: "Menudo",
    protein: "pork",
    baseServings: 4,
    prepMinutes: 20,
    cookMinutes: 50,
    ingredients: [
      { name: "pork", quantity: 700, unit: "g" },
      { name: "tomato sauce", quantity: 200, unit: "g" },
      { name: "potato", quantity: 2, unit: "pcs" },
      { name: "carrot", quantity: 2, unit: "pcs" },
      { name: "green peas", quantity: 1, unit: "cup" },
    ],
    steps: ["Sauté pork with aromatics.", "Add tomato sauce and vegetables.", "Simmer until tender."],
  },
  {
    id: "afritada-chicken",
    name: "Chicken Afritada",
    nameTl: "Afritada",
    protein: "chicken",
    baseServings: 4,
    prepMinutes: 20,
    cookMinutes: 45,
    ingredients: [
      { name: "chicken", quantity: 1, unit: "kg" },
      { name: "tomato sauce", quantity: 200, unit: "g" },
      { name: "potato", quantity: 2, unit: "pcs" },
      { name: "bell pepper", quantity: 2, unit: "pcs" },
    ],
    steps: ["Brown chicken.", "Add tomato sauce and vegetables.", "Simmer until done."],
  },
  {
    id: "laing",
    name: "Laing",
    nameTl: "Laing",
    protein: "veg",
    baseServings: 4,
    prepMinutes: 15,
    cookMinutes: 35,
    ingredients: [
      { name: "taro leaves", quantity: 400, unit: "g" },
      { name: "coconut milk", quantity: 400, unit: "ml" },
      { name: "ginger", quantity: 20, unit: "g" },
      { name: "labuyo", quantity: 3, unit: "pcs" },
    ],
    steps: ["Simmer leaves in coconut milk with ginger.", "Cook until creamy."],
  },
  {
    id: "pancit-canton",
    name: "Pancit Canton",
    nameTl: "Pancit Canton",
    protein: "seafood",
    baseServings: 4,
    prepMinutes: 20,
    cookMinutes: 20,
    ingredients: [
      { name: "canton noodles", quantity: 400, unit: "g" },
      { name: "shrimp", quantity: 300, unit: "g" },
      { name: "cabbage", quantity: 2, unit: "cup" },
      { name: "carrot", quantity: 1, unit: "pcs" },
      { name: "soy sauce", quantity: 3, unit: "tbsp" },
    ],
    steps: ["Stir-fry proteins and vegetables.", "Toss noodles with soy sauce."],
  },
  {
    id: "caldereta",
    name: "Beef Caldereta",
    nameTl: "Kaldereta",
    protein: "beef",
    baseServings: 4,
    prepMinutes: 25,
    cookMinutes: 90,
    ingredients: [
      { name: "beef", quantity: 1, unit: "kg" },
      { name: "liver spread", quantity: 100, unit: "g" },
      { name: "potato", quantity: 2, unit: "pcs" },
      { name: "bell pepper", quantity: 2, unit: "pcs" },
      { name: "tomato sauce", quantity: 150, unit: "g" },
    ],
    steps: ["Brown beef and simmer until tender.", "Add liver spread and vegetables."],
  },
  {
    id: "escabeche",
    name: "Escabeche",
    nameTl: "Escabeche",
    protein: "fish",
    baseServings: 4,
    prepMinutes: 20,
    cookMinutes: 30,
    ingredients: [
      { name: "fish fillet", quantity: 800, unit: "g" },
      { name: "vinegar", quantity: 100, unit: "ml" },
      { name: "carrot", quantity: 1, unit: "pcs" },
      { name: "ginger", quantity: 30, unit: "g" },
    ],
    steps: ["Fry fish until golden.", "Pour sweet-sour vegetable sauce."],
  },
];

export const DAY_LABELS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

export function getRecipeById(id: string): FilipinoRecipe | undefined {
  return FILIPINO_RECIPES.find((r) => r.id === id);
}
